name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build Docker Image and Push to Docker Hub"]
    types:
      - completed

jobs:
  update_server:
    name: update container server-1
    runs-on: ubuntu-latest
    steps:
      - name: conection ssh-v2
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ec2-54-224-139-174.compute-1.amazonaws.com
          user: admin
          key: ${{ secrets.EC2_CHACON_SERVER }}
          connect_timeout: 10s
          script: |
            sudo mkdir prueba1

