name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build Docker Image and Push to Docker Hub"]
    types:
      - completed

jobs:
  update_server:
    name: update container server-1
    runs-on: ubuntu-latest
    steps:
      - name: conection ssh-v7
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ec2-3-89-225-110.compute-1.amazonaws.com
          user: ubuntu
          key: ${{ secrets.EC2_CHACON_SERVER }}
          connect_timeout: 10s
          script: |
            sudo docker pull bettosanchez90/testwf:master
            sudo docker stop front_container && sudo docker rm front_container
            sudo docker run -d -p 80:80 -v /home/ubuntu/configuration_nginx/af_frontend.conf:/etc/nginx/conf.d/default.conf --name front_container bettosanchez90/testwf:master
